<?php

namespace ProjectCmsBundle\Repository;

/**
 * MainPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainPageRepository extends \Doctrine\ORM\EntityRepository
{
}
